name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        working-directory: ebook-convert-rs
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install poppler-utils
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Clippy
        working-directory: ebook-convert-rs
        run: cargo clippy --lib --bins --tests -- -D warnings

  test:
    name: Test
    needs: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install poppler-utils
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Build
        working-directory: ebook-convert-rs
        run: cargo build --all-targets

      - name: Run tests
        working-directory: ebook-convert-rs
        run: cargo test --lib --bins

  build-release:
    name: Build (${{ matrix.name }})
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64
            target: x86_64-unknown-linux-gnu
            binary: ebook-convert-rs
            archive: ebook-convert-rs-linux-x86_64.tar.gz
            cross-pkgs: ""
          - name: linux-aarch64
            target: aarch64-unknown-linux-gnu
            binary: ebook-convert-rs
            archive: ebook-convert-rs-linux-aarch64.tar.gz
            cross-pkgs: gcc-aarch64-linux-gnu
          - name: windows-x86_64
            target: x86_64-pc-windows-gnu
            binary: ebook-convert-rs.exe
            archive: ebook-convert-rs-windows-x86_64.zip
            cross-pkgs: mingw-w64
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation toolchain
        if: matrix.cross-pkgs != ''
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.cross-pkgs }}

      - name: Configure cross-linkers
        if: matrix.cross-pkgs != ''
        shell: bash
        run: |
          mkdir -p ebook-convert-rs/.cargo
          printf '[target.aarch64-unknown-linux-gnu]\nlinker = "aarch64-linux-gnu-gcc"\n\n[target.x86_64-pc-windows-gnu]\nlinker = "x86_64-w64-mingw32-gcc"\nar = "x86_64-w64-mingw32-ar"\n' >> ebook-convert-rs/.cargo/config.toml

      - name: Build release binary
        working-directory: ebook-convert-rs
        run: cargo build --target ${{ matrix.target }} --release

      - name: Package (tar.gz)
        if: "!contains(matrix.archive, '.zip')"
        run: |
          cd ebook-convert-rs/target/${{ matrix.target }}/release
          tar czf ${{ matrix.archive }} ${{ matrix.binary }}
          mv ${{ matrix.archive }} ../../../../

      - name: Package (zip)
        if: contains(matrix.archive, '.zip')
        run: |
          cd ebook-convert-rs/target/${{ matrix.target }}/release
          zip ${{ matrix.archive }} ${{ matrix.binary }}
          mv ${{ matrix.archive }} ../../../../

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.archive }}
          path: ${{ matrix.archive }}
          retention-days: 30
